### ISSUE TITLE
Instrument enif calls

### ISSUE THREAD

**Issue by zv** [tokenrove/niffy#11]
What's happening @tokenrove,

I continue to use niffy quite regularly in tandem with KLEE and valgrind while searching for OTP bugs.  While I've already found some interesting bugs, one of the big challenges is sorting through the events that lead to a particular piece of memory being corrupted or out-of-deadsync. Niffy would be all-that-much cooler with a database for storing telemetry generated on `enif_*` entry and exit, right now I just have an fd that gets a bunch of stuff written to it and is processed with `sort` and `grep`.

stay niffy dude.

P.S: I just has a really embarrassing moment regarding niffy on `erlang-questions`. [Someone posted information about their new project called **nifty**](http://erlang.org/pipermail/erlang-questions/2016-June/089572.html) and having been so excited to write a glowing review of _NIFFY_ I didn't stop to realize it was completely different. My message is in the moderation q, so I'm not sure if it will be posted but if you keep up with erlang listserv you'll have some fanmail, haha.

**Comment by tokenrove** [comment]
I think this is a great idea and am open to proposals in this issue.  Anything in the scope of improving our ability to apply safety and performance tools to NIFs is relevant to niffy.  (And since you mentioned KLEE, that reminds me I need to also try cbmc with niffy, and add a section to the documentation demonstrating the use of various tools like that.)

In terms of my own work on niffy, I have two things that I will work on first: one is completing the enif API coverage, and the other is the benchmarking branch of niffy I haven't finished off.  (The latter includes a wrapper I use for finding slow enif_\* calls that could be adapted for more general instrumentation.)

BTW, great to hear that you are using niffy heavily and thanks for the promo!  I guess I should send a proper niffy announcement to the list, actually; I had been waiting for a few things to stabilize to do a proper release but maybe I'll do that shortly.
